name: hardware/mailserver
description: |
  Simple and full-featured mail server using Docker
version: v1.1-stable-1
maintainer: "Hardware <contact@meshup.net>"
license: MIT License
projectURL: https://github.com/hardware/mailserver
